### ISSUE TITLE
Task list for Sensor Things API in istSOS

### ISSUE THREAD

**Issue by SaailN** [SaailN/istsos2#1]
- [ ] Implementing basic OGC standard Sensor Things API requests for sensing entity.
- [ ] Implementing basic OGC standard Sensor Things API requests for tasking entity
- [ ] Integrating STA service on istSOS
